# Generated by Django 2.1 on 2020-02-18 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='postion',
            new_name='position',
        ),
    ]
