# Generated by Django 2.1 on 2020-02-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0002_auto_20200218_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postion',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
